package:
  name: atk
  version: 2.25.2

source:
  url: http://ftp.gnome.org/pub/gnome/sources/atk/2.25/atk-2.25.2.tar.xz
  sha256: 75ac1f63e845f895dec8d72d4645ef5f362e32c921cc78987f2f19c2ce212a24

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - xz
  host:
    - glib
  run:
    - glib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: http://www.gtk.org/
  summary: Accessibility Toolkit
  license: LGPL
  license_file: COPYING
