{% set major_minor = "2.25" %}
{% set version = major_minor + ".2" %}

package:
  name: atk
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/atk/{{ major_minor }}/atk-{{ version }}.tar.xz
  sha256: 75ac1f63e845f895dec8d72d4645ef5f362e32c921cc78987f2f19c2ce212a24

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - xz
  host:
    - glib
    - gobject-introspection
  run:
    - glib
    - gobject-introspection

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: http://www.gtk.org/
  summary: Accessibility Toolkit
  license: LGPLv2
  license_file: COPYING
