package:
  name: gdk-pixbuf
  version: 2.36.11

source:
  url: https://download.gnome.org/sources/gdk-pixbuf/2.36/gdk-pixbuf-2.36.11.tar.xz
  sha256: ae62ab87250413156ed72ef756347b10208c00e76b222d82d9ed361ed9dde2f3

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - xz
  host:
    - cairo
    - glib
    - gobject-introspection
    - jpeg
    - libffi
    - libpng
    - libtiff
    - pango
    - pcre
    - shared-mime-info
    - zlib
  run:
    - cairo
    - glib
    - gobject-introspection
    - jpeg
    - libffi
    - libpng
    - libtiff
    - pango
    - pcre
    - shared-mime-info
    - zlib

about:
  home: https://gtk.org
  summary: Toolkit for image loading and pixel buffer manipulation
  license: LGPLv2
  license_file: COPYING
