{% set name = "celery" %}
{% set version = "4.1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "77ff3730198d6a17b3c1f05579ebe570b579efb35f6d7e13dba3b1368d068b35" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  entry_points:
    - celery = celery.__main__:main
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytz >dev
    - billiard >=3.5.0.2,<3.6.0
    - kombu >=4.0.2,<5.0
  run:
    - python
    - setuptools
    - pytz >dev
    - billiard >=3.5.0.2,<3.6.0
    - kombu >=4.0.2,<5.0

test:
  imports:
    - celery
    - celery.app
    - celery.apps
    - celery.backends
    - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.contrib.testing
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.task
    - celery.utils
    - celery.utils.dispatch
    - celery.utils.static
    - celery.worker
    - celery.worker.consumer
  commands:
    - celery --version

about:
  home: http://celeryproject.org
  summary: Distributed Task Queue
  license: BSD
  license_file: LICENSE
