package:
  name: guetzli
  version: 1.0.1

source:
  git_url: https://github.com/google/guetzli
  git_tag: v1.0.1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libpng
  run:
    - libpng

test:
  commands:
    - guetzli 2>&1 | grep "Guetzli JPEG compressor"

about:
  home: https://github.com/google/guetzli
  summary: Perceptual JPEG encoder
  license: Apache License 2.0
  license_file: LICENSE
