package:
  name: flask-migrate
  version: 2.0.3

source:
  fn: Flask-Migrate-2.0.3.tar.gz
  url: https://pypi.python.org/packages/a9/fe/559c313679b08f67efb9fba6f01debbc9ea3a488539d03a5a38371351456/Flask-Migrate-2.0.3.tar.gz
  md5: b88ccaef9c8bdc99a197769d09b92a7f

build:
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - alembic >=0.9.5
    - flask >=0.12.2
    - flask-sqlalchemy >=2.1
    - flask-script >=2.0.5
  run:
    - python
    - setuptools
    - alembic >=0.9.5
    - flask >=0.12.2
    - flask-sqlalchemy >=2.1
    - flask-script >=2.0.5

test:
  imports:
    - flask_migrate

about:
  home: http://github.com/miguelgrinberg/flask-migrate
  summary: SQLAlchemy database migrations for Flask applications using Alembic
  license: MIT
  license_file: LICENSE
