package:
  name: flask-cache
  version: 0.13.1

source:
  fn: Flask-Cache-0.13.1.tar.gz
  url: https://pypi.python.org/packages/91/c4/f71095437bd4b691c63f240e72a20c57e2c216085cbc271f79665885d3da/Flask-Cache-0.13.1.tar.gz
  md5: ab82a9cd0844891ccdb54fbb93fd6c59

build:
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - flask >=0.12.2
  run:
    - python
    - setuptools
    - flask >=0.12.2

test:
  imports:
    - flask_cache

about:
  home: http://github.com/thadeusb/flask-cache
  summary: Adds cache support to your Flask application
  license: BSD
  license_file: LICENSE
