{% set name = "tableschema" %}
{% set version = "1.0.12" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "eceb2c2fc9d1977a87c1d394fd4c4d41253b72947b9940c2e33841d197cda90a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - tableschema = tableschema.cli:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - six >=1.9,<2.0
    - click >=3.3,<7.0
    - requests >=2.5,<3.0
    - python-dateutil >=2.4,<3.0
    - jsonschema >=2.5,<3.0
    - unicodecsv >=0.14,<2.0
    - isodate >=0.5.4,<2.0
    - rfc3986 >=1.1.0,<2.0
    - tabulator >=1.3,<2.0
  run:
    - python
    - six >=1.9,<2.0
    - click >=3.3,<7.0
    - requests >=2.5,<3.0
    - python-dateutil >=2.4,<3.0
    - jsonschema >=2.5,<3.0
    - unicodecsv >=0.14,<2.0
    - isodate >=0.5.4,<2.0
    - rfc3986 >=1.1.0,<2.0
    - tabulator >=1.3,<2.0

test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types
  commands:
    - tableschema --help

about:
  home: https://github.com/frictionlessdata/tableschema-py
  summary: A utility library for working with Table Schema in Python
  license: MIT
  license_file: LICENSE.md
