{% set name = "rfc3986" %}
{% set version = "1.1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8458571c4c57e1cf23593ad860bb601b6a604df6217f829c2bc70dc4b5af941b" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - rfc3986

about:
  home: http://rfc3986.readthedocs.io
  summary: Validating URI References per RFC 3986
  license: Apache License 2.0
  license_file: LICENSE
