{% set name = "haversine" %}
{% set version = "0.4.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "56a12298851a455fb80a8d7e8c7c5548b623d5d1bffc9eba16e7855d9eec5c3c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: 'python setup.py install '

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - haversine

about:
  home: https://github.com/mapado/haversine
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Calculate the distance bewteen 2 points on Earth.
  description: 'Haversine

    ---------


    Calculate the distance (in km or in miles) bewteen two points on Earth,

    located by their latitude and longitude.



    Example: distance bewteen Lyon and Paris


    >>> from haversine import haversine

    >>> lyon = (45.7597, 4.8422)

    >>> paris = (48.8567, 2.3508)

    >>> haversine(lyon, paris)

    392.00124794121825  # in kilometers

    >>> haversine(lyon, paris, miles=True)

    243.589575470673  # in miles'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
