package:
  name: fftw
  version: 3.3.7

source:
  url: http://fftw.org/fftw-3.3.7.tar.gz
  md5: 0d5915d7d39b3253c1cc05030d79ac47

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}

about:
    home: http://fftw.org
    summary: The fastest Fourier transform in the west
    license: GPLv3
    license_file: COPYING
