{% set name = "nbdime" %}
{% set version = "0.4.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "86dd00767f8f0ec4f22c9ceaba35130083e737e17de7b9f77ebcab254fd205f2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - nbdime = nbdime.__main__:main_dispatch
    - nbshow = nbdime.nbshowapp:main
    - nbdiff = nbdime.nbdiffapp:main
    - nbdiff-web = nbdime.webapp.nbdiffweb:main
    - nbmerge = nbdime.nbmergeapp:main
    - nbmerge-web = nbdime.webapp.nbmergeweb:main
    - git-nbdiffdriver = nbdime.vcs.git.diffdriver:main
    - git-nbdifftool = nbdime.vcs.git.difftool:main
    - git-nbmergedriver = nbdime.vcs.git.mergedriver:main
    - git-nbmergetool = nbdime.vcs.git.mergetool:main
    - hg-nbdiff = nbdime.vcs.hg.diff:main
    - hg-nbdiffweb = nbdime.vcs.hg.diffweb:main
    - hg-nbmerge = nbdime.vcs.hg.merge:main
    - hg-nbmergeweb = nbdime.vcs.hg.mergeweb:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - nbformat
    - six
    - colorama
    - tornado
    - requests
    - gitpython !=2.1.4,!=2.1.5,!=2.1.6
    - notebook
    - jinja2
  run:
    - python
    - nbformat
    - six
    - colorama
    - tornado
    - requests
    - gitpython !=2.1.4,!=2.1.5,!=2.1.6
    - notebook
    - jinja2

test:
  imports:
    - nbdime
    - nbdime.diffing
    - nbdime.merging
    - nbdime.tests
    - nbdime.vcs
    - nbdime.vcs.git
    - nbdime.vcs.hg
    - nbdime.webapp

about:
  home: http://jupyter.org
  summary: Diff and merge of Jupyter Notebooks
  license: BSD
  license_file: LICENSE.md
