package:
  name: r-base
  version: 3.4.3

source:
  url: https://cran.r-project.org/src/base/R-3/R-3.4.3.tar.gz
  sha256: 7a3cb831de5b4151e1f890113ed207527b7d4b16df9ec6b35e0964170007f426

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  no_link:
    # These files are modified by R CMD javareconf and can
    # point to different Java implementations in each env.
    - lib/R/etc/Makeconf
    - lib/R/etc/ldpaths
    - lib/R/etc/javaconf
    - lib/R/etc/x64/Makeconf
    - lib/R/etc/x64/ldpaths
    - lib/R/etc/x64/javaconf
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - bzip2
    - curl
    - gettext
    - icu
    - jpeg
    - libgcc-ng
    - libpng
    - libtiff
    - libxml2
    - mkl
    - pcre
    - readline
    - zlib
  run:
    - bzip2
    - curl
    - gettext
    - icu
    - jpeg
    - libgcc-ng
    - libpng
    - libtiff
    - libxml2
    - mkl
    - pcre
    - readline
    - zlib

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'

about:
  home: http://www.r-project.org/
  summary: R is a free software environment for statistical computing and graphics
  license: GPLv2
  license_file: COPYING
