{% set name = "DoubleMetaphone" %}
{% set version = "0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ac85b6757b28f5161b24c4aa25a923513a52edebedfa60158eed088ae468cf18" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - doublemetaphone

about:
  home: The package home page
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Python wrapper for C++ Double Metaphone
  description: UNKNOWN
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
