package:
  name: cx_oracle
  version: 6.2.1

source:
  git_url: https://github.com/oracle/python-cx_Oracle
  git_tag: 6.2.1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Oracle

about:
  home: https://github.com/oracle/python-cx_Oracle
  summary: Python interface to Oracle Database
  license: BSD 
  license_file: LICENSE.txt
