{% set name = "tabulator" %}
{% set version = "1.13.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c417008b03f0477c85ef8194b998c1c257c02e08a9e314f147d04856c80950e9" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1
  entry_points:
    - tabulator = tabulator.cli:cli
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.9,<2.0
    - click >=6.0,<7.0
    - requests >=2.8,<3.0
    - cchardet >=1.0,<2.0
    - unicodecsv >=0.14,<2.0
    - ijson >=2.0,<3.0
    - jsonlines >=1.1,<2.0
    - sqlalchemy >=0.9.6,<2.0
    - linear-tsv >=1.0,<2.0
    - xlrd >=1.0,<2.0
    - openpyxl >=2.4,<3.0
  run:
    - python
    - six >=1.9,<2.0
    - click >=6.0,<7.0
    - requests >=2.8,<3.0
    - cchardet >=1.0,<2.0
    - unicodecsv >=0.14,<2.0
    - ijson >=2.0,<3.0
    - jsonlines >=1.1,<2.0
    - sqlalchemy >=0.9.6,<2.0
    - linear-tsv >=1.0,<2.0
    - xlrd >=1.0,<2.0
    - openpyxl >=2.4,<3.0

test:
  imports:
    - tabulator
    - tabulator.loaders
    - tabulator.parsers
    - tabulator.writers
  commands:
    - tabulator --help

about:
  home: https://github.com/frictionlessdata/tabulator-py
  summary: Consistent interface for stream reading and writing tabular data (csv/xls/json/etc)
  license: MIT
  license_file: LICENSE.md
