package:
  name: flask-script
  version: 2.0.5

source:
  fn: Flask-Script-2.0.5.tar.gz
  url: https://pypi.python.org/packages/66/e9/2b3c7c548a6bad0b59da21e2050613da43aae4da617fb98847efa3e09a43/Flask-Script-2.0.5.tar.gz
  md5: e5c73d3b7937f5b88942f342f9617029

build:
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - flask >=0.12.2
  run:
    - python
    - setuptools
    - flask >=0.12.2

test:
  imports:
    - flask_script

about:
  home: http://github.com/smurfix/flask-script
  summary: Scripting support for Flask
  license: BSD
  license_file: LICENSE
