package:
  name: xgboost
  version: 0.7

source:
  git_url: https://github.com/dmlc/xgboost
  git_tag: v0.7

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - libgcc-ng
  host:
    - python
    - setuptools
    - numpy
    - scipy
  run:
    - python
    - setuptools
    - numpy
    - scipy

test:
  imports:
    - xgboost

about:
  home: https://github.com/dmlc/xgboost
  summary: eXtreme Gradient Boosting
  license: Apache 2.0
  license_file: LICENSE
