package:
  name: pandas-profiling
  version: 1.4.1

source:
  git_url: http://github.com/jospolfliet/pandas-profiling
  git_tag: v1.4.1

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pandas
    - matplotlib
    - jinja2
    - six
  run:
    - python
    - setuptools
    - pandas
    - matplotlib
    - jinja2
    - six

test:
  imports:
    - pandas_profiling

about:
  home: http://github.com/jospolfliet/pandas-profiling
  summary: Generate profile report for pandas DataFrame
  license: MIT
  license_file: LICENSE
