package:
  name: libsecret
  version: 0.18.5

source:
  fn: libsecret-0.18.5.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/libsecret/0.18/libsecret-0.18.5.tar.xz
  md5: 2d688825921313da8731313b0a7f394c

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - xz
  host:
    - glib
    - gobject-introspection
    - libffi
    - libgcrypt
    - pcre
    - zlib
  run:
    - glib
    - gobject-introspection
    - libffi
    - libgcrypt
    - pcre
    - zlib

about:
  home: https://wiki.gnome.org/Projects/Libsecret
  summary: library for storing and retrieving passwords and other secrets
  license: LGPLv2
  license_file: COPYING
