package:
  name: intltool
  version: 0.51.0

source:
  url: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
  sha256: 67c74d94196b153b774ab9f89b2fa6c6ba79352407037c8c14d5aeb334e959cd

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config

test:
  commands:
    - intltool-extract --help
    - intltool-update --help

about:
  home: https://wiki.freedesktop.org/www/Software/intltool
  summary: String tool
  license: LGPLv2
  license_file: COPYING
