package:
  name: graphviz
  version: 2.40.1

source:
  url: http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz.tar.gz
  md5: 4ea6fd64603536406166600bcc296fc8

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - cairo
    - expat
    - libpng
    - librsvg
    - libtiff
    - freetype
    - jpeg
    - pango
    - zlib
  run:
    - cairo
    - expat
    - libpng
    - librsvg
    - libtiff
    - freetype
    - jpeg
    - pango
    - zlib

test:
  commands:
    - dot -V
    - neato -?
  files:
    - sample.dot

about:
  home: http://www.graphviz.org/
  summary: Open Source graph visualization software.
  license: EPL
  license_file: COPYING
