package:
  name: shared-mime-info
  version: 1.8

source:
  url: http://freedesktop.org/~hadess/shared-mime-info-1.8.tar.xz
  md5: f6dcadce764605552fc956563efa058c

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - xz
  host:
    - gettext
    - glib
    - libxml2
  run:
    - gettext
    - glib
    - libxml2

test:
  commands:
    - update-mime-database -v

about:
  home: https://wiki.freedesktop.org/www/Software/shared-mime-info
  summary: Database of common MIME types
  license: LGPLv2
  license_file: COPYING
