package:
  name: shap
  version: 0.19.2

source:
  git_url: https://github.com/slundberg/shap
  git_tag: v0.19.2

build:
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - iml
    - matplotlib
    - pandas
    - scikit-learn
    - scipy
    - tqdm
  run:
    - python
    - setuptools
    - iml
    - matplotlib
    - pandas
    - scikit-learn
    - scipy
    - tqdm

test:
  imports:
    - shap
    - shap.explainers

about:
  home: https://github.com/slundberg/shap
  license: MIT
  license_file: LICENSE
  summary: A unified approach to explain the output of any machine learning model
