{% set name = "amqp" %}
{% set version = "2.2.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "cba1ace9d4ff6049b190d8b7991f9c1006b443a5238021aca96dd6ad2ac9da22" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - vine >=1.1.3
  run:
    - python
    - setuptools
    - vine >=1.1.3

test:
  imports:
    - amqp

about:
  home: http://github.com/celery/py-amqp
  summary: Low-level AMQP client for Python (fork of amqplib).
  license: BSD
  license_file: LICENSE
