package:
  name: libgeotiff
  version: 1.4.2

source:
  url: http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-1.4.2.tar.gz
  sha256: ad87048adb91167b07f34974a8e53e4ec356494c29f1748de95252e8f81a5e6e

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - jpeg
    - libtiff
    - proj4
    - zlib
  run:
    - jpeg
    - libtiff
    - proj4
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libgeotiff.so
    - conda inspect linkages -p $PREFIX $PKG_NAME

about:
  home: https://trac.osgeo.org/geotiff
  summary: TIFF based interchange format for georeferenced raster imagery
  license: MIT
  license_file: LICENSE
