package:
  name: pydruid
  version: 0.3.1

source:
  fn: pydruid-0.3.1.tar.gz
  url: https://pypi.python.org/packages/df/f3/349fbdcdbb851149ba2387340b3eb0f1ed53011db5ae15ba119a5f3ea997/pydruid-0.3.1.tar.gz
  md5: ef51c2f40e92000f3fd512f360d47981

build:
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - mock
    - pytest
    - pytest-runner
    - six
  run:
    - python
    - setuptools
    - six

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://pypi.python.org/pypi/pydruid/
  summary: A Python connector for Druid
  license: Apache License 2.0
