{% set name = "perl-extutils-makemaker" %}
{% set version = "7.32" %}
{% set sha256 = "9a269f52ab59b125eb80b968271d9f49da0975d43e51363dbfd1695000ed69de" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: ExtUtils-MakeMaker-7.32.tar.gz
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.32.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
    - perl
  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - ExtUtils::MakeMaker

about:
  home: https://metacpan.org/release/ExtUtils-MakeMaker
  license: Perl
  summary: Create a module Makefile

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
