package:
  name: imagemagick
  version: 7.0.7.22

source:
  fn: ImageMagick-7.0.7-22.tar.gz
  url: https://github.com/ImageMagick/ImageMagick/archive/7.0.7-22.tar.gz
  sha256: ce060a56e6d8a7c51af603dd14d9ded3480a71ce675d7bc2a5532ef1fb737b93

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
  host:
    - bzip2
    - cairo
    - fontconfig
    - freetype
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - pango
    - zlib
  run:
    - bzip2
    - cairo
    - fontconfig
    - freetype
    - jpeg
    - libpng
    - libtiff
    - openjpeg
    - pango
    - zlib

test:
  commands:
    - convert -version
    - convert -list configure | grep DELEGATES | grep png

about:
  home: http://www.imagemagick.org/
  summary: software suite to create, edit, compose, or convert bitmap images
  license: ImageMagick
  license_file: LICENSE
