package:
  name: basemap
  version: 1.1.0

source:
  git_url: https://github.com/matplotlib/basemap
  git_tag: v1.1.0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - geos
    - numpy
    - matplotlib
    - pyproj
    - pyshp
  run:
    - python
    - geos
    - numpy
    - matplotlib
    - pyproj
    - pyshp

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: Plot on map projections using matplotlib
