package:
  name: flower
  version: 0.9.1

source:
  fn: flower-0.9.1.tar.gz
  url: https://pypi.python.org/packages/b4/94/39eff3d8727c03865e6693911a1d84295959238d932603d4dbf2069fe5c9/flower-0.9.1.tar.gz
  md5: 5d191dae0db989b97d9d000133ead843

build:
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - flower = flower.__main__:main

requirements:
  build:
    - python
    - setuptools
    - celery
    - tornado
    - babel
    - pytz
  run:
    - python
    - setuptools
    - celery
    - tornado
    - babel
    - pytz

test:
  imports:
    - flower
    - flower.api
    - flower.utils
    - flower.utils.backports
    - flower.views
  commands:
    - flower --help

about:
  home: https://github.com/mher/flower
  summary: Celery Flower
  license: BSD
  license_file: LICENSE
