package:
  name: fribidi
  version: 1.0.5

source:
  url: https://github.com/fribidi/fribidi/releases/download/v1.0.5/fribidi-1.0.5.tar.bz2
  sha256: 6a64f2a687f5c4f203a46fa659f43dd43d1f8b845df8d723107e8a7e6158e4ce

requirements:
  build:
    - {{ compiler('c') }}

about:
  home: http://fribidi.org/
  summary: implementation of the Unicode Bidirectional Algorithm
  license: LGPL
  license_file: COPYING
