package:
  name: linear-tsv
  version: 1.1.0

source:
  git_url: https://github.com/solidsnack/tsv
  git_tag: 1.1.0

build:
  number: 1
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - six
  run:
    - python
    - setuptools
    - six

test:
  imports:
    - tsv

about:
  home: https://github.com/solidsnack/tsv
  summary: Line-oriented, tab-separated value format
  license: Apache License 2.0
  license_file: LICENSE.txt
