package:
  name: pixman
  version: 0.34.0

source:
  url: http://cairographics.org/releases/pixman-0.34.0.tar.gz
  sha1: a1b1683c1a55acce9d928fea1ab6ceb79142ddc7

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libpng
    - zlib
  run:
    - libpng
    - zlib

about:
  home: http://www.pixman.org/
  summary: A low-level software library for pixel manipulation
  license: MIT
  license_file: COPYING
