{% set version = "2.40.19" %}

package:
  name: librsvg
  version: {{ version }}

source:
  fn: librsvg-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.19.tar.xz
  sha256: 612b4d8b8609036f5d899be3fe70d9866b5f6ac5c971154c1c0ef7242216c1f7

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - xz
  host:
    - cairo
    - gdk-pixbuf
    - glib
    - libcroco
    - pango
  run:
    - cairo
    - gdk-pixbuf
    - glib
    - libcroco
    - pango

test:
  commands:
    - rsvg-convert -v

about:
  home: https://live.gnome.org/LibRsvg
  summary: Library to render SVG files using Cairo
  license: LGPLv2
  license_file: COPYING
