package:
  name: sirad
  version: 0.1.2

source:
  git_url: https://github.com/riipl-org/sirad
  git_tag: v0.1.2

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - jellyfish
    - openpyxl
    - pyyaml
    - sqlalchemy
  run:
    - python
    - setuptools
    - jellyfish
    - openpyxl
    - pyyaml
    - sqlalchemy

test:
  commands:
    - sirad -v

about:
  home: https://github.com/riipl-org/sirad
  summary: "Secure Infrastructure for Research with Administrative Data"
  license: MIT-like
