{% set name = "kombu" %}
{% set version = "4.1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4249d9dd9dbf1fcec471d1c2def20653c9310dd1a217272d77e4844f9d5273cb" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - amqp >=2.1.4,<3.0
    - sqlalchemy
  run:
    - python
    - setuptools
    - amqp >=2.1.4,<3.0
    - sqlalchemy

test:
  imports:
    - kombu
    - kombu.async
    - kombu.async.aws
    - kombu.async.aws.sqs
    - kombu.async.http
    - kombu.transport
    - kombu.transport.sqlalchemy
    - kombu.transport.virtual
    - kombu.utils

about:
  home: https://github.com/celery/kombu
  summary: Messaging library for Python
  license: BSD
  license_file: LICENSE
