package:
  name: r-spatial
  version: 3.4.3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - r-base
    - r-database
    - r-essentials
    - geos
    - libgdal
    - libnetcdf
    - proj4
  run:
    - r-base
    - r-database
    - r-essentials
    - geos
    - libgdal
    - libnetcdf
    - proj4

about:
  home: https://cran.r-project.org/view=Spatial
  summary: "CRAN Task View: Analysis of Spatial Data"
  license: Various
