{% set name = "fastcluster" %}
{% set version = "1.1.24" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a5d1922b1db6f4c3012416e7dc14de2984b9335a48c895e1698afd5c718312b0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy >=1.9
  run:
    - python
    - numpy >=1.9

about:
  home: http://danifold.net
  license: BSD License or GNU General Public License v2 (GPLv2)
  license_family: GPL2
  license_file: ''
  summary: Fast hierarchical clustering routines for R and Python.
  description: "This library provides Python functions for hierarchical clustering. It\ngenerates hierarchical clusters from distance matrices or from vector data.\n\nPart of this module is intended to\
    \ replace the functions ::\n\n    linkage, single, complete, average, weighted, centroid, median, ward\n\nin the module ``scipy.cluster.hierarchy`` with the same functionality but much\nfaster algorithms.\
    \ Moreover, the function ``linkage_vector`` provides\nmemory-efficient clustering for vector data.\n\nThe interface is very similar to MATLAB's Statistics Toolbox API to make code\neasier to port from\
    \ MATLAB to Python/NumPy. The core implementation of this\nlibrary is in C++ for efficiency.\n\n**User manual:** `fastcluster.pdf\n<https://github.com/dmuellner/fastcluster/raw/master/docs/fastcluster.pdf>`_.\n\
    \nInstallation files for Windows are provided on `PyPI\n<https://pypi.python.org/pypi/fastcluster>`_ and on `Christoph Gohlke's web\npage <http://www.lfd.uci.edu/~gohlke/pythonlibs/#fastcluster>`_.\n\
    \n**The fastcluster package is considered stable and will undergo few changes\nfrom now on. If some years from now there have not been any updates, this\ndoes not necessarily mean that the package is\
    \ unmaintained but maybe it just\nwas not necessary to correct anything. Of course, please still report potential\nbugs and incompatibilities to daniel@danifold.net. You may also use**\n`my GitHub repository\
    \ <https://github.com/dmuellner/fastcluster/>`_\n**for bug reports, pull requests etc.**\n\nNote that PyPI and my GitHub repository host the source code for the Python\ninterface only. The archive with\
    \ both the R and the Python interface is\navailable on `CRAN\n<https://CRAN.R-project.org/package=fastcluster>`_ and the\nGitHub repository `\u201Ccran/fastcluster\u201D\n<https://github.com/cran/fastcluster>`_.\
    \ Even though I appear as the author also\nof this second GitHub repository, this is just an automatic, read-only mirror\nof the CRAN archive, so please do not attempt to report bugs or contact me via\n\
    this repository.\n\nReference: Daniel M\xFCllner, *fastcluster: Fast Hierarchical, Agglomerative\nClustering Routines for R and Python*, Journal of Statistical Software, **53**\n(2013), no. 9, 1\u2013\
    18, http://www.jstatsoft.org/v53/i09/."
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
